In [2]:
import numpy as np
import pandas as pd
from pycirclize import Circos

In [3]:
df = pd.read_excel('../data/br2f_topographic_data.xlsx', header=0, index_col=0)

In [4]:
# define left hemisphere
brain_regions = df.index.to_numpy()

left_hemisphere = brain_regions[:392]
df_left_hemisphere = df[left_hemisphere]
df_left_hemisphere = df_left_hemisphere.head(392)

## Hippocampal - Septostri connectivity plots

Next we will look at one aggregated region (LS) and three non-aggregated regions (MS, NDB, ACB) connectivity with the hippocampus. Each of the four regions is an aggregation across other subregions, so we start by summing across the subregions.

In [20]:
# construct regions
LS_aggregated_regions = np.array(['LSr.m.v','LSr.m.d','LSr.vl','LSr.dl','LSc.v','LSc.d','LSv'])

LS_non_aggregated_regions = np.array(['MS','NDB','ACB'])

hippocampus_regions = np.array(['DG','CA3','CA2','CA1v','CA1d','SUBv','SUBd','PAR', 'PRE', 'POST'])

septostri_regions = np.concatenate(
    (LS_aggregated_regions, LS_non_aggregated_regions), axis=0
)

spt_hipp_regions = np.concatenate((septostri_regions, hippocampus_regions), axis=0)

In [21]:
# reduce the left hemisphere dataframe to only include hypothalamus and hippocampal regions
df_spt_hipp = df_left_hemisphere[spt_hipp_regions]
df_spt_hipp = df_spt_hipp[df_spt_hipp.index.isin(spt_hipp_regions)]

In [22]:
def consolidate_sum(dataframe, new_col_row_name, subregion_array):
    ret_df = dataframe
    row_sum = ret_df[ret_df.index.isin(subregion_array)].sum(axis=0)
    ret_df.loc[new_col_row_name] = row_sum
    
    # delete extra subregions from rows
    ret_df = ret_df.loc[
    ~ret_df.index.isin(subregion_array)
    ]
    
    # columns
    col_sum = ret_df[subregion_array].sum(axis=1)
    ret_df.loc[:,new_col_row_name] = col_sum
    
    # delete extra subregion from columns
    ret_df = ret_df.drop(subregion_array, axis=1)
    return ret_df

def consolidate_average(dataframe, new_col_row_name, subregion_array):
    ret_df = dataframe
    row_sum = ret_df[ret_df.index.isin(subregion_array)].mean(axis=0)
    ret_df.loc[new_col_row_name] = row_sum
    
    # delete extra subregions from rows
    ret_df = ret_df.loc[
    ~ret_df.index.isin(subregion_array)
    ]
    
    # columns
    col_sum = ret_df[subregion_array].mean(axis=1)
    ret_df.loc[:,new_col_row_name] = col_sum
    
    # delete extra subregion from columns
    ret_df = ret_df.drop(subregion_array, axis=1)
    return ret_df

In [23]:
df_spt_hipp = consolidate_average(df_spt_hipp, "LS", LS_aggregated_regions)

/var/folders/4k/31jdbs595pn4tslnsm4nxmzm0000gq/T/ipykernel_76503/3939621999.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ret_df.loc[:,new_col_row_name] = col_sum

In [24]:
df_spt_hipp

,MS,NDB,ACB,DG,CA3,CA2,CA1v,CA1d,SUBv,SUBd,PAR,PRE,POST,LS
Abbr.,,,,,,,,,,,,,,
MS,0.000000,5.000000,2.000000,5.000000,3.000000,2.000000,3.000000,2.000000,5.000000,3.0,4.0,2.0,1.0,1.714286
NDB,2.000000,0.000000,0.000000,3.000000,3.000000,1.000000,1.000000,4.000000,2.000000,4.0,6.0,1.0,4.0,1.428571
ACB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
DG,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
CA3,2.000000,2.000000,0.000000,3.000000,0.000000,6.000000,6.000000,6.000000,3.000000,3.0,0.0,0.0,0.0,2.714286
CA2,0.000000,0.000000,0.000000,4.000000,4.000000,0.000000,4.000000,0.000000,3.000000,0.0,2.0,0.0,0.0,1.285714
CA1v,3.000000,3.000000,5.000000,2.000000,1.000000,2.000000,0.000000,0.000000,7.000000,0.0,4.0,2.0,0.0,2.857143
CA1d,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.0,1.0,2.0,0.0,1.857143
SUBv,0.000000,0.000000,6.000000,3.000000,3.000000,3.000000,3.000000,0.000000,0.000000,0.0,5.0,4.0,0.0,3.857143
SUBd,2.000000,2.000000,4.000000,2.000000,3.000000,0.000000,0.000000,4.000000,0.000000,0.0,0.0,0.0,4.0,2.285714
PRE,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,4.0,4.0,0.0,4.0,0.000000
POST,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,4.0,5.0,0.0,0.000000
PAR,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.0,0.0,6.0,1.0,0.000000
LS,1.571429,3.285714,0.571429,0.142857,0.857143,0.142857,0.428571,0.285714,0.285714,0.0,0.0,0.0,0.0,1.081633

In [25]:
# remove self-connections (set diagonal to 0)
for i in range(len(df_spt_hipp.index)):
    df_spt_hipp.iloc[i,i] = 0

In [26]:
# we need to remove connections within the hypothalamus--
# we're only interested in hippocampal-hypothalamus connectivity

septostri_aggregated_regions = np.array(['LS','MS','NDB','ACB'])
for subregion_i in range(len(septostri_aggregated_regions)):
    for subregion_j in range(len(septostri_aggregated_regions)):
        df_spt_hipp.loc[
        septostri_aggregated_regions[subregion_i], 
        septostri_aggregated_regions[subregion_j]
        ] = 0

In [27]:
df_spt_hipp

,MS,NDB,ACB,DG,CA3,CA2,CA1v,CA1d,SUBv,SUBd,PAR,PRE,POST,LS
Abbr.,,,,,,,,,,,,,,
MS,0.0,0.0,0.0,5.000000,3.000000,2.000000,3.000000,2.000000,5.000000,3.0,4.0,2.0,1.0,0.000000
NDB,0.0,0.0,0.0,3.000000,3.000000,1.000000,1.000000,4.000000,2.000000,4.0,6.0,1.0,4.0,0.000000
ACB,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
DG,0.0,0.0,0.0,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
CA3,2.0,2.0,0.0,3.000000,0.000000,6.000000,6.000000,6.000000,3.000000,3.0,0.0,0.0,0.0,2.714286
CA2,0.0,0.0,0.0,4.000000,4.000000,0.000000,4.000000,0.000000,3.000000,0.0,2.0,0.0,0.0,1.285714
CA1v,3.0,3.0,5.0,2.000000,1.000000,2.000000,0.000000,0.000000,7.000000,0.0,4.0,2.0,0.0,2.857143
CA1d,0.0,1.0,1.0,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.0,1.0,2.0,0.0,1.857143
SUBv,0.0,0.0,6.0,3.000000,3.000000,3.000000,3.000000,0.000000,0.000000,0.0,5.0,4.0,0.0,3.857143
SUBd,2.0,2.0,4.0,2.000000,3.000000,0.000000,0.000000,4.000000,0.000000,0.0,0.0,0.0,4.0,2.285714
PRE,0.0,0.0,0.0,2.000000,2.000000,2.000000,2.000000,2.000000,4.000000,4.0,0.0,0.0,4.0,0.000000
POST,0.0,0.0,0.0,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,4.0,0.0,0.0,0.000000
PAR,0.0,0.0,0.0,2.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.0,0.0,6.0,0.0,0.000000
LS,0.0,0.0,0.0,0.142857,0.857143,0.142857,0.428571,0.285714,0.285714,0.0,0.0,0.0,0.0,0.000000

In [28]:
#clear out intrinsic connections between hippocampus_regions
for subregion_i in range(len(hippocampus_regions)):
    for subregion_j in range(len(hippocampus_regions)):
        df_spt_hipp.loc[
        hippocampus_regions[subregion_i], 
        hippocampus_regions[subregion_j]
        ] = 0

In [29]:
df_spt_hipp

,MS,NDB,ACB,DG,CA3,CA2,CA1v,CA1d,SUBv,SUBd,PAR,PRE,POST,LS
Abbr.,,,,,,,,,,,,,,
MS,0.0,0.0,0.0,5.000000,3.000000,2.000000,3.000000,2.000000,5.000000,3.0,4.0,2.0,1.0,0.000000
NDB,0.0,0.0,0.0,3.000000,3.000000,1.000000,1.000000,4.000000,2.000000,4.0,6.0,1.0,4.0,0.000000
ACB,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
DG,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
CA3,2.0,2.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.714286
CA2,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.285714
CA1v,3.0,3.0,5.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.857143
CA1d,0.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.857143
SUBv,0.0,0.0,6.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,3.857143
SUBd,2.0,2.0,4.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.285714
PRE,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
POST,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
PAR,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000
LS,0.0,0.0,0.0,0.142857,0.857143,0.142857,0.428571,0.285714,0.285714,0.0,0.0,0.0,0.0,0.000000

In [30]:
# delete rows with all 0's
df_spt_hipp_cleaned = df_spt_hipp.loc[(df_spt_hipp.T!=0).any(),:]

In [31]:
df_spt_hipp_cleaned

,MS,NDB,ACB,DG,CA3,CA2,CA1v,CA1d,SUBv,SUBd,PAR,PRE,POST,LS
Abbr.,,,,,,,,,,,,,,
MS,0.0,0.0,0.0,5.000000,3.000000,2.000000,3.000000,2.000000,5.000000,3.0,4.0,2.0,1.0,0.000000
NDB,0.0,0.0,0.0,3.000000,3.000000,1.000000,1.000000,4.000000,2.000000,4.0,6.0,1.0,4.0,0.000000
CA3,2.0,2.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.714286
CA2,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.285714
CA1v,3.0,3.0,5.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.857143
CA1d,0.0,1.0,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,1.857143
SUBv,0.0,0.0,6.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,3.857143
SUBd,2.0,2.0,4.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,2.285714
LS,0.0,0.0,0.0,0.142857,0.857143,0.142857,0.428571,0.285714,0.285714,0.0,0.0,0.0,0.0,0.000000

In [32]:
# re-order rows for more coherent representation in plot

df_spt_hipp_cleaned = df_spt_hipp_cleaned.loc[
['CA1v','CA1d','CA2','CA3','SUBv','SUBd','MS','NDB','LS'],
['CA1v','CA1d','CA2','CA3','DG','PAR','PRE','POST','SUBv','SUBd','MS','NDB','ACB','LS']
]

In [33]:
df_spt_hipp_cleaned

,CA1v,CA1d,CA2,CA3,DG,PAR,PRE,POST,SUBv,SUBd,MS,NDB,ACB,LS
Abbr.,,,,,,,,,,,,,,
CA1v,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,3.0,3.0,5.0,2.857143
CA1d,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,1.0,1.0,1.857143
CA2,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,1.285714
CA3,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,2.0,2.0,0.0,2.714286
SUBv,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,6.0,3.857143
SUBd,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,2.0,2.0,4.0,2.285714
MS,3.000000,2.000000,2.000000,3.000000,5.000000,4.0,2.0,1.0,5.000000,3.0,0.0,0.0,0.0,0.000000
NDB,1.000000,4.000000,1.000000,3.000000,3.000000,6.0,1.0,4.0,2.000000,4.0,0.0,0.0,0.0,0.000000
LS,0.428571,0.285714,0.142857,0.857143,0.142857,0.0,0.0,0.0,0.285714,0.0,0.0,0.0,0.0,0.000000

In [34]:
circos_hyp_hipp_extrinsic_only = Circos.initialize_from_matrix(df_spt_hipp_cleaned, 
                                                               space=5,
                                                               cmap="jet")

circos_hyp_hipp_extrinsic_only.savefig("../output/hippocampus_septostri_extrinsic_average_connectivity.svg")